In [2]:
import pandas as pd
import numpy as np

## From Theory class

### `Replace()`

In [3]:
#create a dataset with columns 'Name' and 'City'
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve','Manuel'],
        'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix','phoenix']}
df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix
5   Manuel      phoenix

In [4]:
#replace 'phoenix' with 'Phoenix' in the 'City' column
df['City'] = df['City'].replace('phoenix', 'Phoenix')
print("\nDataFrame after replacement:")
df

DataFrame after replacement:

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago
3    David      Houston
4      Eve      Phoenix
5   Manuel      Phoenix

### `Map()`

In [5]:
#create a dataset with columns 'Name' and 'City'
data = {'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eve'],
        'City': ['Lisbon', 'Porto', 'Évora', 'Barcelona', 'Madrid']}
df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

      Name       City
0    Alice     Lisbon
1      Bob      Porto
2  Charlie      Évora
3    David  Barcelona
4      Eve     Madrid

In [6]:
#create a mapping dictionary to map cities to their respective countries
city_to_country = {
    'Lisbon': 'Portugal',
    'Porto': 'Portugal',
    'Évora': 'Portugal',
    'Barcelona': 'Spain',
    'Madrid': 'Spain'
}
#use the map function to create a new column 'Country' based on the 'City' column
df['Country'] = df['City'].map(city_to_country)
print("\nDataFrame after mapping:")
df

DataFrame after mapping:

      Name       City   Country
0    Alice     Lisbon  Portugal
1      Bob      Porto  Portugal
2  Charlie      Évora  Portugal
3    David  Barcelona     Spain
4      Eve     Madrid     Spain

### `Apply()`

In [7]:
#create a dataset with columns 'Movie' and list of 'Genre'
data = {'Movie': ['Inception', 'The Matrix', 'Interstellar', 'The Godfather', 'Pulp Fiction'],
        'Genre': [['Action', 'Sci-Fi'], ['Action', 'Sci-Fi'], ['Adventure', 'Sci-Fi'], ['Crime', 'Drama'], ['Crime', 'Drama']]}
df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

           Movie                Genre
0      Inception     [Action, Sci-Fi]
1     The Matrix     [Action, Sci-Fi]
2   Interstellar  [Adventure, Sci-Fi]
3  The Godfather       [Crime, Drama]
4   Pulp Fiction       [Crime, Drama]

In [8]:
#from the 'Genre' column, a new column with the length of the list of genres and also new only with genres thats starts with 'A'
df['Genre_Count'] = df['Genre'].apply(len)
df['Genres_Start_with_A'] = df['Genre'].apply(lambda genres: [genre for genre in genres if genre.startswith('A')])
print("\nDataFrame after applying functions:")
df

DataFrame after applying functions:

           Movie                Genre  Genre_Count Genres_Start_with_A
0      Inception     [Action, Sci-Fi]            2            [Action]
1     The Matrix     [Action, Sci-Fi]            2            [Action]
2   Interstellar  [Adventure, Sci-Fi]            2         [Adventure]
3  The Godfather       [Crime, Drama]            2                  []
4   Pulp Fiction       [Crime, Drama]            2                  []

In [9]:
# create a dataset with columns 'city' and 'temperature' in Fahrenheit
data = {'City': ['New York', 'Los Angeles', 'Chicago', 'Houston', 'Phoenix'],
        'Temperature_F': [75, 85, 70, 90, 100]}
df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

          City  Temperature_F
0     New York             75
1  Los Angeles             85
2      Chicago             70
3      Houston             90
4      Phoenix            100

In [10]:
#using vectorize ops to convert the temperature from Fahrenheit to Celsius
df['Temperature_C'] = (df['Temperature_F'] - 32) * 5.0/9.0
print("\nDataFrame after vectorized operation:")
df

DataFrame after vectorized operation:

          City  Temperature_F  Temperature_C
0     New York             75      23.888889
1  Los Angeles             85      29.444444
2      Chicago             70      21.111111
3      Houston             90      32.222222
4      Phoenix            100      37.777778

### Merge Inner

In [11]:
#create two datasets with a common column 'ID'
data1 = {'ID': [1, 2, 3, 4],
         'Name': ['Alice', 'Bob', 'Charlie', 'David']}
df1 = pd.DataFrame(data1)

print("DataFrame 1:")
df1

DataFrame 1:

   ID     Name
0   1    Alice
1   2      Bob
2   3  Charlie
3   4    David

In [12]:
data2 = {'ID': [3, 4, 5, 6],
         'City': ['Chicago', 'Houston', 'Phoenix', 'Philadelphia']}
df2 = pd.DataFrame(data2)
print("DataFrame 2:")
df2

DataFrame 2:

   ID          City
0   3       Chicago
1   4       Houston
2   5       Phoenix
3   6  Philadelphia

In [13]:
#merge the two datasets on the 'ID' column using an inner join
merged_df = pd.merge(df1, df2, on='ID', how='inner')
print("Merged DataFrame (Inner Join):")
merged_df

Merged DataFrame (Inner Join):

   ID     Name     City
0   3  Charlie  Chicago
1   4    David  Houston

In [14]:
#now testing the left and right join
#left join
left_merged_df = pd.merge(df1, df2, on='ID', how='left')
print("Merged DataFrame (Left Join):")
left_merged_df

Merged DataFrame (Left Join):

   ID     Name     City
0   1    Alice      NaN
1   2      Bob      NaN
2   3  Charlie  Chicago
3   4    David  Houston

In [15]:
#right join
right_merged_df = pd.merge(df1, df2, on='ID', how='right')
print("Merged DataFrame (Right Join):")
right_merged_df

Merged DataFrame (Right Join):

   ID     Name          City
0   3  Charlie       Chicago
1   4    David       Houston
2   5      NaN       Phoenix
3   6      NaN  Philadelphia

In [16]:
#outer join
outer_merged_df = pd.merge(df1, df2, on='ID', how='outer')
print("Merged DataFrame (Outer Join):")
outer_merged_df

Merged DataFrame (Outer Join):

   ID     Name          City
0   1    Alice           NaN
1   2      Bob           NaN
2   3  Charlie       Chicago
3   4    David       Houston
4   5      NaN       Phoenix
5   6      NaN  Philadelphia

### Concatenation

In [17]:
#create two datasets with the same columns 'Name' and 'City'
data1 = {'Name': ['Alice', 'Bob', 'Charlie'],
         'City': ['New York', 'Los Angeles', 'Chicago']}
df1 = pd.DataFrame(data1)
print("DataFrame 1:")
df1

DataFrame 1:

      Name         City
0    Alice     New York
1      Bob  Los Angeles
2  Charlie      Chicago

In [18]:
data2 = {'Name': ['David', 'Eve', 'Frank'],
         'City': ['Houston', 'Phoenix', 'Philadelphia']}
df2 = pd.DataFrame(data2)
print("DataFrame 2:")
df2

DataFrame 2:

    Name          City
0  David       Houston
1    Eve       Phoenix
2  Frank  Philadelphia

In [19]:
#concatenate the two datasets vertically (stacking rows)
concatenated_df = pd.concat([df1, df2], ignore_index=True)
print("Concatenated DataFrame (Vertical):")
concatenated_df

Concatenated DataFrame (Vertical):

      Name          City
0    Alice      New York
1      Bob   Los Angeles
2  Charlie       Chicago
3    David       Houston
4      Eve       Phoenix
5    Frank  Philadelphia

In [20]:
#concatenate the two datasets horizontally (stacking columns)
concatenated_df_horizontal = pd.concat([df1, df2], axis=1)
print("Concatenated DataFrame (Horizontal):")
concatenated_df_horizontal

Concatenated DataFrame (Horizontal):

      Name         City   Name          City
0    Alice     New York  David       Houston
1      Bob  Los Angeles    Eve       Phoenix
2  Charlie      Chicago  Frank  Philadelphia

### Reshaping with `Melt()`

In [21]:
#create a dataset with columns 'Name', 'Math_Score', and 'English_Score'
data = {'Name': ['Alice', 'Bob', 'Charlie'],
        'Math_Score': [85, 90, 78],
        'English_Score': [92, 88, 80]}
df = pd.DataFrame(data)
print("Original DataFrame:")
df

Original DataFrame:

      Name  Math_Score  English_Score
0    Alice          85             92
1      Bob          90             88
2  Charlie          78             80

In [22]:
#use the melt function to reshape the dataset from wide format to long format
melted_df = pd.melt(df, id_vars=['Name'], var_name='Subject', value_name='Score')
print("Melted DataFrame:")
melted_df

Melted DataFrame:

      Name        Subject  Score
0    Alice     Math_Score     85
1      Bob     Math_Score     90
2  Charlie     Math_Score     78
3    Alice  English_Score     92
4      Bob  English_Score     88
5  Charlie  English_Score     80

## Exercises

### Exercício de Consolidação
Usando o dataframe `auto` que carregamos anteriormente, responda às seguintes perguntas:
1. Qual é a média do preço dos carros por tipo de motor?
2. Qual é a marca com o maior número de carros listados?
3. Qual é a média milhas por marca?
4. Separe horsepower em 3 classes, baixo, médio e alto e calculo a media do preço e mileage.
5. Qual é o top 5 carros mais caros?
6. Qual é o top 5 carros mais baratos?
7. Agrupe por engine-type e por num-of-cylinders e calcule a média do preço.

### Desafio de Consolidação 2
Utilizando o dataframe `netflix` que carregamos anteriormente, responda às seguintes perguntas:
1. Segmente o dataset netflix em dois. netflix_movies e netflix_tvshows?
2. Quantos filmes e quantas séries estão disponíveis na plataforma?
3. Qual é o género que possui mais filmes na plataforma?
4. Localize e liste as series que possuem a palavra "love" em sua descrição.
5. Qual é a média de duração dos filmes por género para filmes?
6. Qual é a média de Seasons por género para séries?
7. Qual é o top 5 filmes mais longos?
8. Qual é o top 5 séries com mais seasons?

### Desafio de Consolidação 3
Considerando as tabelas ecomerce e clientes responda:
1. Quais as profissoes que fizeram a maior quantidade de compras
2. Quais as profissoes que mais gastaram
3. Qual foi o ano-mes que mais vederam produtos (valor)