In [1]:
import pandas as pd

# Consolidação de Conhecimentos em Pandas

Ao longo das aulas anteriores, tivemos o primeiro contacto com a biblioteca **pandas**, explorando os seus principais conceitos e ferramentas para manipulação de dados em Python. Este notebook surge agora com um novo objetivo: **consolidar esse conhecimento**.

Mais do que introduzir novos conteúdos de forma isolada, a proposta aqui é reforçar aquilo que já foi aprendido, aprofundar a compreensão dos conceitos fundamentais e esclarecer dúvidas que surgiram — especialmente aquelas identificadas em avaliações anteriores.

A consolidação é uma etapa essencial no processo de aprendizagem. É neste momento que deixamos de apenas reconhecer conceitos para **os aplicar com segurança e autonomia**. Por isso, ao longo deste notebook, serão revisitados temas importantes como:

- Estruturas fundamentais do pandas (Series e DataFrames)
- Leitura e escrita de dados
- Seleção e filtragem
- Manipulação e transformação de dados
- Tratamento de valores em falta

Este trabalho também servirá como preparação para o próximo passo: **Data Wrangling** — o processo de limpeza, transformação e organização de dados brutos em formatos adequados para análise.

A ideia é que, ao final desta revisão, estejam mais confiantes na utilização do pandas e mais preparados para lidar com problemas reais de dados.

Vamos a isso !


---

## Series vs DataFrame

No **pandas**, existem duas estruturas de dados fundamentais: **Series** e **DataFrame**. Compreender bem a diferença entre estas duas estruturas é essencial, pois praticamente todas as operações que realizamos vão envolver uma delas.

### Series

Uma **Series** é uma estrutura de dados **unidimensional**, ou seja, funciona como uma lista ou uma coluna de uma tabela.

- Possui **um único eixo** (valores)
- Cada elemento está associado a um **índice**
- Pode armazenar qualquer tipo de dados (inteiros, strings, floats, etc.)

In [33]:
obj2 = pd.Series([4, 7,-5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
#selecionar uma linha passando o nome do indice
print(obj2["a"])

-5

In [6]:
#iloc funciona
print(obj2.iloc[2])

-5

In [8]:
#loc também
print(obj2.loc["c"])

3

In [7]:
#filtros em serie de dados. Aqui nao precisa indicar a coluna. Só tem uma coluna
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [9]:
#operacoes com todos os elementos da serie
print(obj2 * 2)

d     8
b    14
a   -10
c     6
dtype: int64

In [10]:
#quando iterage com a serie o que acontece
for i in obj2:
    print(i)

#quando iteragem com um dataframe o que acontecia??

4
7
-5
3

In [11]:
#operador in aqui testa um index e nao um valor
"b" in obj2

True

In [13]:
#criando uma serie a partir de um dicionário
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3
#portanto nao precisa criar como fizemos antes, a partir de duas listas. Awui ele ja identifica as chaves do dicionário como indices e os valores como os dados da serie

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [14]:
#da pra voltar de uma serie para um dicionário
a = obj3.to_dict()
print(a)

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [15]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
#se passar uma key que nao estiver no dicionário ele coloca NaN
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [21]:
#ja aprendemos a localizar NaN
pd.isnull(obj4)

# #ou
# pd.notnull(obj4)
# #ou
# pd.isna(obj4)
# #ou
# pd.notna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [22]:
#da pra usar operador "+" em duas series
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [23]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [24]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [25]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [27]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [30]:
#posso editar indices a qualquer momento
obj = pd.Series([4, 7,-5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [31]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
dtype: int64

### DataFrame

Um **DataFrame** é uma estrutura **bidimensional**, ou seja, uma tabela com linhas e colunas.

- Possui **dois eixos** (linhas e colunas)
- Cada coluna é, na prática, uma **Series**
- Permite armazenar diferentes tipos de dados em colunas diferentes

In [35]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [37]:
#head e tail
frame.head(3) #padrao é 5

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9

In [38]:
frame.tail(3) #padrao é 5

    state  year  pop
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [42]:
pd.DataFrame(data, columns=["year", "state", "pop"]) #isso cria um dataframe mas precisa ser igualado a uma variavel para guardar
#o mesmo que
# frame[["year", "state", "pop"]] #portanto isso nao muda o original, apenas mostra a ordem diferente

   year   state  pop
0  2000    Ohio  1.5
1  2001    Ohio  1.7
2  2002    Ohio  3.6
3  2001  Nevada  2.4
4  2002  Nevada  2.9
5  2003  Nevada  3.2

In [43]:
frame

    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [44]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"]) #passando uma coluna que nao existe ele cria a coluna mas com NaN
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [48]:
#quando iteragem com um dataframe
for i in frame2:
    print(i)

print("-"*20)
#na serie retornava os valores das linhas
for i in obj2:
    print(i)

year
state
pop
debt
--------------------
4
7
-5
3

In [50]:
#voltando para o dataframe
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [51]:
#obter os dados de uma coluna
frame2["state"]

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

In [53]:
a = frame2["state"]
print(type(a))

#se quiser em lista tem que ser
b = frame2["state"].tolist()
print(type(b))

<class 'pandas.Series'>
<class 'list'>

In [54]:
#jeito mais "escondido"
frame2.state

0      Ohio
1      Ohio
2      Ohio
3    Nevada
4    Nevada
5    Nevada
Name: state, dtype: str

`frame2[column]` works for any column name, but frame2.column works only when the column name is a valid Python variable name and does not conflict with any of the method names in DataFrame.

For example, if a column’s name contains whitespace or symbols other than underscores, it cannot be accessed with the dot attribute method.

In [56]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year of": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame3 = pd.DataFrame(data, columns=["year of", "state", "pop", "debt"]) #passando uma coluna que nao existe ele cria a coluna mas com NaN
frame3["year of"]

0    2000
1    2001
2    2002
3    2001
4    2002
5    2003
Name: year of, dtype: int64

In [59]:
frame3.year of

SyntaxError: invalid syntax (581157305.py, line 1)

In [60]:
#voltando a frame2
frame2

   year   state  pop debt
0  2000    Ohio  1.5  NaN
1  2001    Ohio  1.7  NaN
2  2002    Ohio  3.6  NaN
3  2001  Nevada  2.4  NaN
4  2002  Nevada  2.9  NaN
5  2003  Nevada  3.2  NaN

In [61]:
frame2["debt"] = 16.5
frame2

   year   state  pop  debt
0  2000    Ohio  1.5  16.5
1  2001    Ohio  1.7  16.5
2  2002    Ohio  3.6  16.5
3  2001  Nevada  2.4  16.5
4  2002  Nevada  2.9  16.5
5  2003  Nevada  3.2  16.5

In [64]:
#pode ser uma lista
lista_debt = [16.5, 5, 17.5, 100, 18.5, 19.5]
frame2["debt"] = lista_debt
frame2

   year   state  pop   debt
0  2000    Ohio  1.5   16.5
1  2001    Ohio  1.7    5.0
2  2002    Ohio  3.6   17.5
3  2001  Nevada  2.4  100.0
4  2002  Nevada  2.9   18.5
5  2003  Nevada  3.2   19.5

In [65]:
# um indice é importante pq quando importo dados posso aproveitar e colocar dados em lugares especificos
val = pd.Series([-1.2, -1.5, -1.7], index=[0, 2, 3]) #aqui usando uma serie com index em expecificos
frame2

   year   state  pop   debt  val
0  2000    Ohio  1.5   16.5 -1.2
1  2001    Ohio  1.7    5.0  NaN
2  2002    Ohio  3.6   17.5 -1.5
3  2001  Nevada  2.4  100.0 -1.7
4  2002  Nevada  2.9   18.5  NaN
5  2003  Nevada  3.2   19.5  NaN

In [66]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

   year   state  pop   debt  val  eastern
0  2000    Ohio  1.5   16.5 -1.2     True
1  2001    Ohio  1.7    5.0  NaN     True
2  2002    Ohio  3.6   17.5 -1.5     True
3  2001  Nevada  2.4  100.0 -1.7    False
4  2002  Nevada  2.9   18.5  NaN    False
5  2003  Nevada  3.2   19.5  NaN    False

In [67]:
frame2.eastern2 = frame2["state"] == "Ohio"
frame2

/var/folders/wv/lsjsk14j2hs2j2fw_6d4mtpm0000gn/T/ipykernel_8950/2131565667.py:1: UserWarning: Pandas doesn't allow columns to be created via a new attribute name - see https://pandas.pydata.org/pandas-docs/stable/indexing.html#attribute-access
  frame2.eastern2 = frame2["state"] == "Ohio"

   year   state  pop   debt  val  eastern
0  2000    Ohio  1.5   16.5 -1.2     True
1  2001    Ohio  1.7    5.0  NaN     True
2  2002    Ohio  3.6   17.5 -1.5     True
3  2001  Nevada  2.4  100.0 -1.7    False
4  2002  Nevada  2.9   18.5  NaN    False
5  2003  Nevada  3.2   19.5  NaN    False

In [68]:
#removendo uma coluna
del frame2["eastern"]
frame2

   year   state  pop   debt  val
0  2000    Ohio  1.5   16.5 -1.2
1  2001    Ohio  1.7    5.0  NaN
2  2002    Ohio  3.6   17.5 -1.5
3  2001  Nevada  2.4  100.0 -1.7
4  2002  Nevada  2.9   18.5  NaN
5  2003  Nevada  3.2   19.5  NaN

In [69]:
#transpondo o dataframe
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [70]:
frame3.T

        2000  2001  2002
Ohio     1.5   1.7   3.6
Nevada   NaN   2.4   2.9

In [71]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

      Ohio  Nevada
2001   1.7     2.4
2002   3.6     2.9
2003   NaN     NaN

![Possible data inputs to the DataFrame constructor](table1.png)

## O Index no Pandas

O **Index** é um dos elementos fundamentais no pandas e está presente tanto em **Series** quanto em **DataFrames**. Ele funciona como um conjunto de **rótulos (labels)** que identificam cada linha (e também cada coluna, no caso de DataFrames).

### O que é o Index?

Podemos pensar no **Index** como o "nome" ou "identificador" de cada linha.

- É **imutável** (não pode ser alterado diretamente)
- Garante o **alinhamento dos dados** em operações
- Pode conter valores únicos ou repetidos (embora o ideal seja serem únicos)

---

In [76]:
obj = pd.Series([1,2,3], index=["a", "b", "c"])
obj

a    1
b    2
c    3
dtype: int64

In [77]:
index_serie = obj.index
print(index_serie)

Index(['a', 'b', 'c'], dtype='str')

In [78]:
index_serie[1]

'b'

In [79]:
index_serie[1] = "d" #isso da erro pq o index é imutável

TypeError: Index does not support mutable operations

In [80]:
frame3

      Ohio  Nevada
2000   1.5     NaN
2001   1.7     2.4
2002   3.6     2.9

In [81]:
index_columns = frame3.columns
print(index_columns)

Index(['Ohio', 'Nevada'], dtype='str')

In [82]:
index_columns[1]

'Nevada'

In [83]:
index_columns[1] = "estado" #isso da erro pq o index é imutável

TypeError: Index does not support mutable operations

## Funcionalidades Essenciais no Pandas

Depois de consolidarmos as estruturas fundamentais do pandas — como **Series**, **DataFrames** e **Index** — o próximo passo é explorar as **operações essenciais** que nos permitem trabalhar com os dados de forma prática.

No dia a dia, utilizar pandas não é apenas armazenar dados, mas sim **transformá-los, reorganizá-los e extrair informação relevante**. É aqui que entram as funcionalidades centrais da biblioteca, que tornam possível:

- Ajustar e reorganizar estruturas de dados
- Remover ou modificar informação
- Selecionar subconjuntos de dados
- Realizar operações entre diferentes conjuntos de dados
- Aplicar funções de forma eficiente

Estas operações formam a base de praticamente todo o trabalho com dados em pandas. Em vez de abordar cada conceito apenas de forma teórica, vamos explorá-los diretamente através de **exemplos práticos em código**, de modo a reforçar a intuição e a capacidade de aplicação.

O objetivo é que, ao trabalhar com estes exemplos, consigam reconhecer padrões e desenvolver confiança para resolver problemas reais de manipulação de dados.

In [84]:
obj = pd.Series([4.5, 7.2,-5.3, 3.6], index=["d", "b", "a", "c"])
obj

d    4.5
b    7.2
a   -5.3
c    3.6
dtype: float64

In [86]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2
#portanto ele mantei os valores da serie anterior e para os valores que nao existe ele coloca NaN

a   -5.3
b    7.2
c    3.6
d    4.5
e    NaN
dtype: float64

In [87]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

0      blue
2    purple
4    yellow
dtype: str

In [88]:
obj3.reindex(range(6), method="ffill") #ffill é forward fill, ou seja, preenche os valores NaN com o valor anterior

0      blue
1      blue
2    purple
3    purple
4    yellow
5    yellow
dtype: str

In [89]:
#dropping entries
obj = pd.Series([2,3,4,5,6], index=["a", "b", "c", "d", "e"])
obj

a    2
b    3
c    4
d    5
e    6
dtype: int64

In [94]:
new_obj = obj.drop("c")
obj

a    2
b    3
c    4
d    5
e    6
dtype: int64

In [95]:
new_obj

a    2
b    3
d    5
e    6
dtype: int64

In [96]:
obj.drop(["d", "c"])

a    2
b    3
e    6
dtype: int64

In [97]:
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [98]:
data.drop(index=["Colorado", "Ohio"])

          one  two  three  four
Utah        8    9     10    11
New York   12   13     14    15

In [102]:
data.drop("two", axis=1)

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [103]:
data.drop("two", axis="columns")

          one  three  four
Ohio        0      2     3
Colorado    4      6     7
Utah        8     10    11
New York   12     14    15

In [104]:
data.drop("Ohio", axis=0)

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [105]:
data.drop("Ohio", axis=1)

KeyError: "['Ohio'] not found in axis"

In [107]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [112]:
obj["b"]

np.float64(1.0)

In [113]:
obj[1]

KeyError: 1

In [114]:
obj[1:]

b    1.0
c    2.0
d    3.0
dtype: float64

In [116]:
obj[["b","c"]]

b    1.0
c    2.0
dtype: float64

In [117]:
obj

a    0.0
b    1.0
c    2.0
d    3.0
dtype: float64

In [119]:
obj["b":"c"]

b    1.0
c    2.0
dtype: float64

In [120]:
obj["a":"c"]

a    0.0
b    1.0
c    2.0
dtype: float64

In [122]:
obj["b":]

b    1.0
c    2.0
d    3.0
dtype: float64

In [124]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"],columns=["one", "two", "three", "four"])
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [125]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [126]:
#decompondo as componentes do filtro
data["three"] > 5

Ohio        False
Colorado     True
Utah         True
New York     True
Name: three, dtype: bool

In [127]:
#ou
lista_bool = [False, True, True, True]

data[lista_bool]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [129]:
data[data["three"] > 5]

          one  two  three  four
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [130]:
#da pra transformar o dataframe em um dataframe booleano
data > 5

            one    two  three   four
Ohio      False  False  False  False
Colorado  False  False   True   True
Utah       True   True   True   True
New York   True   True   True   True

![Indexing options with DataFrame](table2.png)

In [132]:
#da pra acessar um valor usando endereço negativo?
ser = pd.Series(np.arange(3.))
ser

0    0.0
1    1.0
2    2.0
dtype: float64

In [133]:
ser[0]

np.float64(0.0)

In [134]:
ser[-1] #isso da erro, nao funciona com endereço negativo

KeyError: -1

In [139]:
data

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15

In [140]:
data.loc[:, "one"] = 1
data

          one  two  three  four
Ohio        1    1      2     3
Colorado    1    5      6     7
Utah        1    9     10    11
New York    1   13     14    15

In [142]:
#ou
data["one"] = 5
data

          one  two  three  four
Ohio        5    1      2     3
Colorado    5    5      6     7
Utah        5    9     10    11
New York    5   13     14    15

In [143]:
s1 = pd.Series([7.3,-2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6,-1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [144]:
s1 + s2 #só soma os valores que tem o mesmo indice, os outros ficam com NaN

a    5.2
c    1.1
d    NaN
e    0.0
f    NaN
g    NaN
dtype: float64

In [145]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [147]:
df1

            b    c    d
Ohio      0.0  1.0  2.0
Texas     3.0  4.0  5.0
Colorado  6.0  7.0  8.0

In [148]:
df2

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [146]:
df1 + df2 #soma os valores que tem o mesmo indice e mesma coluna, os outros ficam com NaN

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [150]:
#criar dataframe a partir de uma lista de discionários
data = [{"a": i, "b": 2 * i} for i in range(3)]
pd.DataFrame(data)
#orientado a linhas

   a  b
0  0  0
1  1  2
2  2  4

In [151]:
#criar um dataframe a partir de um dicionário com listas
data = {
    "name":["a", "b", "c"],
    "age":[20, 30, 40],
    "city":["NY", "LA", "Chicago"]
}
pd.DataFrame(data)
#orientado a colunas

  name  age     city
0    a   20       NY
1    b   30       LA
2    c   40  Chicago

In [152]:
df3 = df1 + df2
df3

            b   c     d   e
Colorado  NaN NaN   NaN NaN
Ohio      3.0 NaN   6.0 NaN
Oregon    NaN NaN   NaN NaN
Texas     9.0 NaN  12.0 NaN
Utah      NaN NaN   NaN NaN

In [156]:
df3.fillna(0) #preenche os valores NaN com 0

            b    c     d     e
Colorado  6.0  7.0   8.0   0.0
Ohio      3.0  1.0   6.0   5.0
Oregon    9.0  0.0  10.0  11.0
Texas     9.0  4.0  12.0   8.0
Utah      0.0  0.0   1.0   2.0

In [157]:
1/df3 #isso é o mesmo que df3.rdiv(1), ou seja, divide 1 por cada elemento do dataframe, e os NaN continuam NaN

                 b         c         d         e
Colorado  0.166667  0.142857  0.125000       NaN
Ohio      0.333333  1.000000  0.166667  0.200000
Oregon    0.111111       NaN  0.100000  0.090909
Texas     0.111111  0.250000  0.083333  0.125000
Utah           inf       NaN  1.000000  0.500000

In [162]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0

In [163]:
series = frame.iloc[0]
series

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64

In [164]:
frame - series
#matches the index of the Series to the columns of the DataFrame and performs the subtraction

          b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [171]:
#aplicando funcoes
frame = pd.DataFrame(np.random.standard_normal((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame

               b         d         e
Utah    0.079134 -0.214434  1.190364
Ohio   -0.122965  1.435553 -0.657558
Texas  -0.309042 -1.031761  0.875179
Oregon -0.190603 -1.445766 -0.428386

In [173]:
np.abs(frame)
#usando funcoes diretas do numpy no dataframe, ele aplica a função a cada elemento do dataframe

               b         d         e
Utah    0.079134  0.214434  1.190364
Ohio    0.122965  1.435553  0.657558
Texas   0.309042  1.031761  0.875179
Oregon  0.190603  1.445766  0.428386

In [177]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1) #aplica a função f1 a cada coluna do dataframe, ou seja, calcula a diferença entre o valor máximo e mínimo de cada coluna

b    0.388176
d    2.881319
e    1.847923
dtype: float64

In [178]:
frame.apply(f1, axis="columns") #aplica a função f1 a cada linha do dataframe, ou seja, calcula a diferença entre o valor máximo e mínimo de cada linha

Utah      1.404798
Ohio      2.093112
Texas     1.906941
Oregon    1.255163
dtype: float64

In [181]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

a = frame.apply(f2) #aplica a função f2 a cada coluna do dataframe, ou seja, calcula o valor mínimo e máximo de cada coluna e retorna uma série com esses valores
a

            b         d         e
min -0.309042 -1.445766 -0.657558
max  0.079134  1.435553  1.190364

In [182]:
type(a)

pandas.DataFrame

In [183]:
frame

               b         d         e
Utah    0.079134 -0.214434  1.190364
Ohio   -0.122965  1.435553 -0.657558
Texas  -0.309042 -1.031761  0.875179
Oregon -0.190603 -1.445766 -0.428386

In [187]:
frame["e"]

Utah      1.190364
Ohio     -0.657558
Texas     0.875179
Oregon   -0.428386
Name: e, dtype: float64

In [188]:
def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

            b      d      e
Utah     0.08  -0.21   1.19
Ohio    -0.12   1.44  -0.66
Texas   -0.31  -1.03   0.88
Oregon  -0.19  -1.45  -0.43

In [189]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [190]:
obj.sort_index()

a    1
b    2
c    3
d    0
dtype: int64

In [198]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [199]:
frame.sort_index()

       d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [206]:
frame

       d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [207]:
frame.sort_index(axis="columns", ascending=True)

       a  b  c  d
three  1  2  3  0
one    5  6  7  4

In [208]:
frame.sort_values(by="a",ascending=False)

       d  a  b  c
one    4  5  6  7
three  0  1  2  3