In [2]:
import pandas as pd

# Consolidação de Conhecimentos em Pandas

Ao longo das aulas anteriores, tivemos o primeiro contacto com a biblioteca **pandas**, explorando os seus principais conceitos e ferramentas para manipulação de dados em Python. Este notebook surge agora com um novo objetivo: **consolidar esse conhecimento**.

Mais do que introduzir novos conteúdos de forma isolada, a proposta aqui é reforçar aquilo que já foi aprendido, aprofundar a compreensão dos conceitos fundamentais e esclarecer dúvidas que surgiram — especialmente aquelas identificadas em avaliações anteriores.

A consolidação é uma etapa essencial no processo de aprendizagem. É neste momento que deixamos de apenas reconhecer conceitos para **os aplicar com segurança e autonomia**. Por isso, ao longo deste notebook, serão revisitados temas importantes como:

- Estruturas fundamentais do pandas (Series e DataFrames)
- Leitura e escrita de dados
- Seleção e filtragem
- Manipulação e transformação de dados
- Tratamento de valores em falta

Este trabalho também servirá como preparação para o próximo passo: **Data Wrangling** — o processo de limpeza, transformação e organização de dados brutos em formatos adequados para análise.

A ideia é que, ao final desta revisão, estejam mais confiantes na utilização do pandas e mais preparados para lidar com problemas reais de dados.

Vamos a isso !


---

## Series vs DataFrame

No **pandas**, existem duas estruturas de dados fundamentais: **Series** e **DataFrame**. Compreender bem a diferença entre estas duas estruturas é essencial, pois praticamente todas as operações que realizamos vão envolver uma delas.

### Series

Uma **Series** é uma estrutura de dados **unidimensional**, ou seja, funciona como uma lista ou uma coluna de uma tabela.

- Possui **um único eixo** (valores)
- Cada elemento está associado a um **índice**
- Pode armazenar qualquer tipo de dados (inteiros, strings, floats, etc.)

In [3]:
obj2 = pd.Series([4, 7,-5, 3], index=["d", "b", "a", "c"])
obj2

d    4
b    7
a   -5
c    3
dtype: int64

In [4]:
#selecionar uma linha passando o nome do indice
print(obj2["a"])

-5

In [5]:
#iloc funciona
print(obj2.iloc[2])

-5

In [6]:
#loc também
print(obj2.loc["c"])

3

In [7]:
#filtros em serie de dados. Aqui nao precisa indicar a coluna. Só tem uma coluna
obj2[obj2 > 0]

d    4
b    7
c    3
dtype: int64

In [8]:
#operacoes com todos os elementos da serie
print(obj2 * 2)

d     8
b    14
a   -10
c     6
dtype: int64

In [9]:
#quando iterage com a serie o que acontece
for i in obj2:
    print(i)

#quando iteragem com um dataframe o que acontecia??

4
7
-5
3

In [10]:
#operador in aqui testa um index e nao um valor
"b" in obj2

True

In [11]:
#criando uma serie a partir de um dicionário
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
obj3 = pd.Series(sdata)
obj3
#portanto nao precisa criar como fizemos antes, a partir de duas listas. Awui ele ja identifica as chaves do dicionário como indices e os valores como os dados da serie

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [12]:
#da pra voltar de uma serie para um dicionário
a = obj3.to_dict()
print(a)

{'Ohio': 35000, 'Texas': 71000, 'Oregon': 16000, 'Utah': 5000}

In [13]:
sdata = {"Ohio": 35000, "Texas": 71000, "Oregon": 16000, "Utah": 5000}
#se passar uma key que nao estiver no dicionário ele coloca NaN
states = ["California", "Ohio", "Oregon", "Texas"]
obj4 = pd.Series(sdata, index=states)
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [14]:
#ja aprendemos a localizar NaN
pd.isnull(obj4)

# #ou
# pd.notnull(obj4)
# #ou
# pd.isna(obj4)
# #ou
# pd.notna(obj4)

California     True
Ohio          False
Oregon        False
Texas         False
dtype: bool

In [15]:
#da pra usar operador "+" em duas series
obj3

Ohio      35000
Texas     71000
Oregon    16000
Utah       5000
dtype: int64

In [16]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [17]:
obj3 + obj4

California         NaN
Ohio           70000.0
Oregon         32000.0
Texas         142000.0
Utah               NaN
dtype: float64

In [18]:
obj4

California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
dtype: float64

In [19]:
obj4.name = "population"
obj4.index.name = "state"
obj4

state
California        NaN
Ohio          35000.0
Oregon        16000.0
Texas         71000.0
Name: population, dtype: float64

In [20]:
#posso editar indices a qualquer momento
obj = pd.Series([4, 7,-5, 3])
obj

0    4
1    7
2   -5
3    3
dtype: int64

In [21]:
obj.index = ["Bob", "Steve", "Jeff", "Ryan"]
obj.name = "um"
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
Name: um, dtype: int64

In [22]:
obj

Bob      4
Steve    7
Jeff    -5
Ryan     3
Name: um, dtype: int64

In [23]:
obj2 = pd.Series([1, 1,0, 0])
obj2.index = ["Bob", "Steve", "Jeff", "Jack"]
obj2.name = "dois"

obj2

Bob      1
Steve    1
Jeff     0
Jack     0
Name: dois, dtype: int64

In [24]:
#concatenate serie obj e obj2
obj4 = pd.concat([obj, obj2],axis=1) #axis=1 para concatenar horizontalmente, ou seja, criar um dataframe com as duas series como colunas
obj4

        um  dois
Bob    4.0   1.0
Steve  7.0   1.0
Jeff  -5.0   0.0
Ryan   3.0   NaN
Jack   NaN   0.0

In [25]:
b = obj4["Bob"]
type(b)

KeyError: 'Bob'

### DataFrame

Um **DataFrame** é uma estrutura **bidimensional**, ou seja, uma tabela com linhas e colunas.

- Possui **dois eixos** (linhas e colunas)
- Cada coluna é, na prática, uma **Series**
- Permite armazenar diferentes tipos de dados em colunas diferentes

In [ ]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}

frame = pd.DataFrame(data)
frame

In [ ]:
#head e tail
frame.head(3) #padrao é 5

In [ ]:
frame.tail(3) #padrao é 5

In [ ]:
pd.DataFrame(data, columns=["year", "state", "pop"]) #isso cria um dataframe mas precisa ser igualado a uma variavel para guardar
#o mesmo que
# frame[["year", "state", "pop"]] #portanto isso nao muda o original, apenas mostra a ordem diferente

In [ ]:
frame

In [ ]:
frame2 = pd.DataFrame(data, columns=["year", "state", "pop", "debt"]) #passando uma coluna que nao existe ele cria a coluna mas com NaN
frame2

In [ ]:
#quando iteragem com um dataframe
for i in frame2:
    print(i)
    for j in frame2[i].to_list():
        print(j)

    print()

print("-"*20)
#na serie retornava os valores das linhas
for i in obj2:
    print(i)

In [ ]:
#voltando para o dataframe
frame2

In [ ]:
#obter os dados de uma coluna
a = frame2["state"]
print(type(a))

In [ ]:
a = frame2["state"]
print(type(a))

#se quiser em lista tem que ser
b = frame2["state"].tolist()
print(type(b))

In [ ]:
#jeito mais "escondido"
frame2.state

`frame2[column]` works for any column name, but frame2.column works only when the column name is a valid Python variable name and does not conflict with any of the method names in DataFrame.

For example, if a column’s name contains whitespace or symbols other than underscores, it cannot be accessed with the dot attribute method.

In [ ]:
data = {"state": ["Ohio", "Ohio", "Ohio", "Nevada", "Nevada", "Nevada"],
        "year of": [2000, 2001, 2002, 2001, 2002, 2003],
        "pop": [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
frame3 = pd.DataFrame(data, columns=["year of", "state", "pop", "debt"]) #passando uma coluna que nao existe ele cria a coluna mas com NaN
frame3["year of"]

In [ ]:
frame3.year of

In [ ]:
#voltando a frame2
frame2

In [ ]:
frame2["debt"] = 16.5
frame2

In [ ]:
frame2

In [ ]:
obj2

In [ ]:
#pode ser uma lista
# lista_debt = [16.5, 5, 17.5, 100, 18.5, 19.5]
lista_debt = pd.Series([16.5, 5, 17.5, 100, 18.5, 19.5, 50,100,78])
frame2["zuil"] = obj2
frame2

In [ ]:
# um indice é importante pq quando importo dados posso aproveitar e colocar dados em lugares especificos
val = pd.Series([-1.2, -1.5, -1.7], index=[0, 2, 3]) #aqui usando uma serie com index em expecificos
frame2

In [ ]:
frame2["eastern"] = frame2["state"] == "Ohio"
frame2

In [ ]:
frame2.eastern2 = frame2["state"] == "Ohio"
frame2

In [ ]:
frame2

In [ ]:
#removendo uma coluna
del frame2["zuil"]
frame2

In [ ]:
a = frame2.pop("zuil")
print(a)

In [ ]:
frame2

In [ ]:
#transpondo o dataframe
populations = {"Ohio": {2000: 1.5, 2001: 1.7, 2002: 3.6},"Nevada": {2001: 2.4, 2002: 2.9}}
frame3 = pd.DataFrame(populations)
frame3

In [ ]:
frame3.T

In [ ]:
pd.DataFrame(populations, index=[2001, 2002, 2003])

![Possible data inputs to the DataFrame constructor](table1.png)

## O Index no Pandas

O **Index** é um dos elementos fundamentais no pandas e está presente tanto em **Series** quanto em **DataFrames**. Ele funciona como um conjunto de **rótulos (labels)** que identificam cada linha (e também cada coluna, no caso de DataFrames).

### O que é o Index?

Podemos pensar no **Index** como o "nome" ou "identificador" de cada linha.

- É **imutável** (não pode ser alterado diretamente)
- Garante o **alinhamento dos dados** em operações
- Pode conter valores únicos ou repetidos (embora o ideal seja serem únicos)

---

In [ ]:
obj = pd.Series([1,2,3], index=["a", "b", "c"])
obj

In [ ]:
index_serie = obj.index
print(index_serie)

In [ ]:
index_serie[1]

In [ ]:
index_serie[1] = "d" #isso da erro pq o index é imutável

In [ ]:
frame3

In [ ]:
index_columns = frame3.columns
print(index_columns)

In [ ]:
index_columns[1]

In [ ]:
index_columns[1] = "estado" #isso da erro pq o index é imutável

## Funcionalidades Essenciais no Pandas

Depois de consolidarmos as estruturas fundamentais do pandas — como **Series**, **DataFrames** e **Index** — o próximo passo é explorar as **operações essenciais** que nos permitem trabalhar com os dados de forma prática.

No dia a dia, utilizar pandas não é apenas armazenar dados, mas sim **transformá-los, reorganizá-los e extrair informação relevante**. É aqui que entram as funcionalidades centrais da biblioteca, que tornam possível:

- Ajustar e reorganizar estruturas de dados
- Remover ou modificar informação
- Selecionar subconjuntos de dados
- Realizar operações entre diferentes conjuntos de dados
- Aplicar funções de forma eficiente

Estas operações formam a base de praticamente todo o trabalho com dados em pandas. Em vez de abordar cada conceito apenas de forma teórica, vamos explorá-los diretamente através de **exemplos práticos em código**, de modo a reforçar a intuição e a capacidade de aplicação.

O objetivo é que, ao trabalhar com estes exemplos, consigam reconhecer padrões e desenvolver confiança para resolver problemas reais de manipulação de dados.

In [ ]:
obj = pd.Series([4.5, 7.2,-5.3, 3.6], index=["d", "b", "a", "c"])
obj

In [ ]:
obj2 = obj.reindex(["a", "b", "c", "d", "e"])
obj2
#portanto ele mantei os valores da serie anterior e para os valores que nao existe ele coloca NaN

In [ ]:
obj3 = pd.Series(["blue", "purple", "yellow"], index=[0, 2, 4])
obj3

In [ ]:
obj3.reindex(range(6), method="ffill") #ffill é forward fill, ou seja, preenche os valores NaN com o valor anterior

In [ ]:
#dropping entries
obj = pd.Series([2,3,4,5,6], index=["a", "b", "c", "d", "e"])
obj

In [ ]:
new_obj = obj.drop("c")
obj

In [ ]:
new_obj

In [ ]:
obj.drop(["d", "c"])

In [ ]:
import numpy as np
data = pd.DataFrame(np.arange(16).reshape((4, 4)), index=["Ohio", "Colorado", "Utah", "New York"], columns=["one", "two", "three", "four"])
data

In [ ]:
data.drop(index=["Colorado", "Ohio"])

In [ ]:
data.drop("two", axis=1)

In [ ]:
data.drop("two", axis="columns")

In [ ]:
data.drop("Ohio", axis=0)

In [ ]:
data.drop("Ohio", axis=1)

In [ ]:
obj = pd.Series(np.arange(4.), index=["a", "b", "c", "d"])
obj

In [ ]:
obj["b"]

In [ ]:
obj[1]

In [ ]:
obj[1:]

In [ ]:
obj[["b","c"]]

In [ ]:
obj

In [ ]:
obj["b":"c"]

In [ ]:
obj["a":"c"]

In [ ]:
obj["b":]

In [ ]:
data = pd.DataFrame(np.arange(16).reshape((4, 4)),index=["Ohio", "Colorado", "Utah", "New York"],columns=["one", "two", "three", "four"])
data

In [ ]:
data[data["three"] > 5]

In [ ]:
#decompondo as componentes do filtro
data[(data["three"] > 5 & data["four"] > 3)]

In [ ]:
#ou
lista_bool = [False, True, True, True]

data[lista_bool]

In [ ]:
data[data["three"] > 5]

In [ ]:
#da pra transformar o dataframe em um dataframe booleano
data > 5

![Indexing options with DataFrame](table2.png)

In [ ]:
#da pra acessar um valor usando endereço negativo?
ser = pd.Series(np.arange(3.))
ser

In [ ]:
ser[0]

In [ ]:
ser[-1] #isso da erro, nao funciona com endereço negativo

In [ ]:
data

In [ ]:
data.loc[:, "one"] = 1
data

In [ ]:
#ou
data["one"] = 5
data

In [ ]:
s1 = pd.Series([7.3,-2.5, 3.4, 1.5], index=["a", "c", "d", "e"])
s2 = pd.Series([-2.1, 3.6,-1.5, 4, 3.1],index=["a", "c", "e", "f", "g"])

In [ ]:
s1 + s2 #só soma os valores que tem o mesmo indice, os outros ficam com NaN

In [ ]:
df1 = pd.DataFrame(np.arange(9.).reshape((3, 3)), columns=list("bcd"),index=["Ohio", "Texas", "Colorado"])
df2 = pd.DataFrame(np.arange(12.).reshape((4, 3)), columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])

In [ ]:
df1

In [ ]:
df2

In [ ]:
df1 + df2 #soma os valores que tem o mesmo indice e mesma coluna, os outros ficam com NaN

In [ ]:
#criar dataframe a partir de uma lista de discionários
data = [{"a": i, "b": 2 * i} for i in range(3)]
pd.DataFrame(data)
#orientado a linhas

In [ ]:
#criar um dataframe a partir de um dicionário com listas
data = {
    "name":["a", "b", "c"],
    "age":[20, 30, 40],
    "city":["NY", "LA", "Chicago"]
}
pd.DataFrame(data)
#orientado a colunas

In [ ]:
#criar um dicionário a partir de uma lista de dicionários
data = [{"name": "a", "age": 20, "city": "NY"},
        {"name": "b", "age": 30, "city": "LA"},
        {"name": "c", "age": 40, "city": "Chicago"}]
pd.DataFrame(data)

In [ ]:
df3 = df1 + df2
df3

In [ ]:
df3.fillna(0) #preenche os valores NaN com 0

In [ ]:
1/df3 #isso é o mesmo que df3.rdiv(1), ou seja, divide 1 por cada elemento do dataframe, e os NaN continuam NaN

In [ ]:
frame = pd.DataFrame(np.arange(12.).reshape((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame

In [ ]:
series = frame.iloc[0]
series

In [ ]:
frame - series
#matches the index of the Series to the columns of the DataFrame and performs the subtraction

In [ ]:
#aplicando funcoes
frame = pd.DataFrame(np.random.standard_normal((4, 3)),columns=list("bde"),index=["Utah", "Ohio", "Texas", "Oregon"])
frame

In [ ]:
np.abs(frame)
#usando funcoes diretas do numpy no dataframe, ele aplica a função a cada elemento do dataframe

In [ ]:
def f1(x):
    return x.max() - x.min()

frame.apply(f1) #aplica a função f1 a cada coluna do dataframe, ou seja, calcula a diferença entre o valor máximo e mínimo de cada coluna

In [ ]:
frame.apply(f1, axis="columns") #aplica a função f1 a cada linha do dataframe, ou seja, calcula a diferença entre o valor máximo e mínimo de cada linha

In [ ]:
def f2(x):
    return pd.Series([x.min(), x.max()], index=["min", "max"])

a = frame.apply(f2) #aplica a função f2 a cada coluna do dataframe, ou seja, calcula o valor mínimo e máximo de cada coluna e retorna uma série com esses valores
a

In [ ]:
type(a)

In [ ]:
frame

In [ ]:
frame["e"]

In [ ]:
def my_format(x):
    return f"{x:.2f}"

frame.map(my_format)

In [ ]:
obj = pd.Series(np.arange(4), index=["d", "a", "b", "c"])
obj

In [ ]:
obj.sort_index()

In [ ]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=["three", "one"],
                     columns=["d", "a", "b", "c"])
frame

In [ ]:
frame.sort_index()

In [ ]:
frame

In [ ]:
frame.sort_index(axis="columns", ascending=True)

In [ ]:
frame.sort_values(by="a",ascending=False)

In [27]:
frame = pd.DataFrame({"b": [4, 7,-3, 2], "a": [0, 1, 0, 1]})
frame

   b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [28]:
frame.sort_values(["a", "b"])

   b  a
2 -3  0
0  4  0
3  2  1
1  7  1